//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV13 {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AccountServiceSoapBinding", Namespace="https://adwords.google.com/api/adwords/v13")]
    public partial class AccountService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private useragent useragentValueField;
        
        private password passwordValueField;
        
        private email emailValueField;
        
        private clientEmail clientEmailValueField;
        
        private clientCustomerId clientCustomerIdValueField;
        
        private developerToken developerTokenValueField;
        
        private applicationToken applicationTokenValueField;
        
        private responseTime responseTimeValueField;
        
        private operations operationsValueField;
        
        private units unitsValueField;
        
        private requestId requestIdValueField;
        
        private System.Threading.SendOrPostCallback getAccountInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getClientAccountInfosOperationCompleted;
        
        private System.Threading.SendOrPostCallback getClientAccountsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMccAlertsOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateAccountInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AccountService() {
            this.Url = global::Easynet.Edge.Services.Google.Adwords.Properties.Settings.Default.Edge_Services_Google_Adwords_GAdWordsAccountServiceV13_AccountService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public useragent useragentValue {
            get {
                return this.useragentValueField;
            }
            set {
                this.useragentValueField = value;
            }
        }
        
        public password passwordValue {
            get {
                return this.passwordValueField;
            }
            set {
                this.passwordValueField = value;
            }
        }
        
        public email emailValue {
            get {
                return this.emailValueField;
            }
            set {
                this.emailValueField = value;
            }
        }
        
        public clientEmail clientEmailValue {
            get {
                return this.clientEmailValueField;
            }
            set {
                this.clientEmailValueField = value;
            }
        }
        
        public clientCustomerId clientCustomerIdValue {
            get {
                return this.clientCustomerIdValueField;
            }
            set {
                this.clientCustomerIdValueField = value;
            }
        }
        
        public developerToken developerTokenValue {
            get {
                return this.developerTokenValueField;
            }
            set {
                this.developerTokenValueField = value;
            }
        }
        
        public applicationToken applicationTokenValue {
            get {
                return this.applicationTokenValueField;
            }
            set {
                this.applicationTokenValueField = value;
            }
        }
        
        public responseTime responseTimeValue {
            get {
                return this.responseTimeValueField;
            }
            set {
                this.responseTimeValueField = value;
            }
        }
        
        public operations operationsValue {
            get {
                return this.operationsValueField;
            }
            set {
                this.operationsValueField = value;
            }
        }
        
        public units unitsValue {
            get {
                return this.unitsValueField;
            }
            set {
                this.unitsValueField = value;
            }
        }
        
        public requestId requestIdValue {
            get {
                return this.requestIdValueField;
            }
            set {
                this.requestIdValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getAccountInfoCompletedEventHandler getAccountInfoCompleted;
        
        /// <remarks/>
        public event getClientAccountInfosCompletedEventHandler getClientAccountInfosCompleted;
        
        /// <remarks/>
        public event getClientAccountsCompletedEventHandler getClientAccountsCompleted;
        
        /// <remarks/>
        public event getMccAlertsCompletedEventHandler getMccAlertsCompleted;
        
        /// <remarks/>
        public event updateAccountInfoCompletedEventHandler updateAccountInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("responseTimeValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("unitsValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("emailValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("applicationTokenValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("requestIdValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("clientCustomerIdValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("passwordValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("developerTokenValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("operationsValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("clientEmailValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("useragentValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="https://adwords.google.com/api/adwords/v13", ResponseNamespace="https://adwords.google.com/api/adwords/v13", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getAccountInfoReturn")]
        public AccountInfo getAccountInfo() {
            object[] results = this.Invoke("getAccountInfo", new object[0]);
            return ((AccountInfo)(results[0]));
        }
        
        /// <remarks/>
        public void getAccountInfoAsync() {
            this.getAccountInfoAsync(null);
        }
        
        /// <remarks/>
        public void getAccountInfoAsync(object userState) {
            if ((this.getAccountInfoOperationCompleted == null)) {
                this.getAccountInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAccountInfoOperationCompleted);
            }
            this.InvokeAsync("getAccountInfo", new object[0], this.getAccountInfoOperationCompleted, userState);
        }
        
        private void OngetAccountInfoOperationCompleted(object arg) {
            if ((this.getAccountInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAccountInfoCompleted(this, new getAccountInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("responseTimeValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("unitsValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("emailValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("applicationTokenValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("requestIdValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("clientCustomerIdValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("passwordValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("developerTokenValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("operationsValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("clientEmailValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("useragentValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="https://adwords.google.com/api/adwords/v13", ResponseNamespace="https://adwords.google.com/api/adwords/v13", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getClientAccountInfosReturn")]
        public ClientAccountInfo[] getClientAccountInfos() {
            object[] results = this.Invoke("getClientAccountInfos", new object[0]);
            return ((ClientAccountInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void getClientAccountInfosAsync() {
            this.getClientAccountInfosAsync(null);
        }
        
        /// <remarks/>
        public void getClientAccountInfosAsync(object userState) {
            if ((this.getClientAccountInfosOperationCompleted == null)) {
                this.getClientAccountInfosOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetClientAccountInfosOperationCompleted);
            }
            this.InvokeAsync("getClientAccountInfos", new object[0], this.getClientAccountInfosOperationCompleted, userState);
        }
        
        private void OngetClientAccountInfosOperationCompleted(object arg) {
            if ((this.getClientAccountInfosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getClientAccountInfosCompleted(this, new getClientAccountInfosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("responseTimeValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("unitsValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("emailValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("applicationTokenValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("requestIdValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("clientCustomerIdValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("passwordValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("developerTokenValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("operationsValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("clientEmailValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("useragentValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="https://adwords.google.com/api/adwords/v13", ResponseNamespace="https://adwords.google.com/api/adwords/v13", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getClientAccountsReturn")]
        public string[] getClientAccounts() {
            object[] results = this.Invoke("getClientAccounts", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getClientAccountsAsync() {
            this.getClientAccountsAsync(null);
        }
        
        /// <remarks/>
        public void getClientAccountsAsync(object userState) {
            if ((this.getClientAccountsOperationCompleted == null)) {
                this.getClientAccountsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetClientAccountsOperationCompleted);
            }
            this.InvokeAsync("getClientAccounts", new object[0], this.getClientAccountsOperationCompleted, userState);
        }
        
        private void OngetClientAccountsOperationCompleted(object arg) {
            if ((this.getClientAccountsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getClientAccountsCompleted(this, new getClientAccountsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("responseTimeValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("unitsValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("emailValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("applicationTokenValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("requestIdValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("clientCustomerIdValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("passwordValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("developerTokenValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("operationsValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("clientEmailValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("useragentValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="https://adwords.google.com/api/adwords/v13", ResponseNamespace="https://adwords.google.com/api/adwords/v13", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getMccAlertsReturn")]
        public MccAlert[] getMccAlerts() {
            object[] results = this.Invoke("getMccAlerts", new object[0]);
            return ((MccAlert[])(results[0]));
        }
        
        /// <remarks/>
        public void getMccAlertsAsync() {
            this.getMccAlertsAsync(null);
        }
        
        /// <remarks/>
        public void getMccAlertsAsync(object userState) {
            if ((this.getMccAlertsOperationCompleted == null)) {
                this.getMccAlertsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMccAlertsOperationCompleted);
            }
            this.InvokeAsync("getMccAlerts", new object[0], this.getMccAlertsOperationCompleted, userState);
        }
        
        private void OngetMccAlertsOperationCompleted(object arg) {
            if ((this.getMccAlertsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMccAlertsCompleted(this, new getMccAlertsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("responseTimeValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("unitsValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("emailValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("applicationTokenValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("requestIdValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("clientCustomerIdValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("passwordValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("developerTokenValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("operationsValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("clientEmailValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("useragentValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="https://adwords.google.com/api/adwords/v13", ResponseNamespace="https://adwords.google.com/api/adwords/v13", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updateAccountInfo(AccountInfo accountInfo) {
            this.Invoke("updateAccountInfo", new object[] {
                        accountInfo});
        }
        
        /// <remarks/>
        public void updateAccountInfoAsync(AccountInfo accountInfo) {
            this.updateAccountInfoAsync(accountInfo, null);
        }
        
        /// <remarks/>
        public void updateAccountInfoAsync(AccountInfo accountInfo, object userState) {
            if ((this.updateAccountInfoOperationCompleted == null)) {
                this.updateAccountInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateAccountInfoOperationCompleted);
            }
            this.InvokeAsync("updateAccountInfo", new object[] {
                        accountInfo}, this.updateAccountInfoOperationCompleted, userState);
        }
        
        private void OnupdateAccountInfoOperationCompleted(object arg) {
            if ((this.updateAccountInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateAccountInfoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://adwords.google.com/api/adwords/v13", IsNullable=false)]
    public partial class responseTime : System.Web.Services.Protocols.SoapHeader {
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://adwords.google.com/api/adwords/v13", IsNullable=false)]
    public partial class units : System.Web.Services.Protocols.SoapHeader {
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://adwords.google.com/api/adwords/v13", IsNullable=false)]
    public partial class email : System.Web.Services.Protocols.SoapHeader {
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://adwords.google.com/api/adwords/v13", IsNullable=false)]
    public partial class applicationToken : System.Web.Services.Protocols.SoapHeader {
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://adwords.google.com/api/adwords/v13", IsNullable=false)]
    public partial class requestId : System.Web.Services.Protocols.SoapHeader {
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://adwords.google.com/api/adwords/v13", IsNullable=false)]
    public partial class clientCustomerId : System.Web.Services.Protocols.SoapHeader {
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://adwords.google.com/api/adwords/v13", IsNullable=false)]
    public partial class password : System.Web.Services.Protocols.SoapHeader {
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://adwords.google.com/api/adwords/v13", IsNullable=false)]
    public partial class developerToken : System.Web.Services.Protocols.SoapHeader {
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://adwords.google.com/api/adwords/v13", IsNullable=false)]
    public partial class operations : System.Web.Services.Protocols.SoapHeader {
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://adwords.google.com/api/adwords/v13", IsNullable=false)]
    public partial class clientEmail : System.Web.Services.Protocols.SoapHeader {
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://adwords.google.com/api/adwords/v13", IsNullable=false)]
    public partial class useragent : System.Web.Services.Protocols.SoapHeader {
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    public partial class AccountInfo {
        
        private Address billingAddressField;
        
        private string currencyCodeField;
        
        private System.Nullable<long> customerIdField;
        
        private bool customerIdFieldSpecified;
        
        private NetworkType[] defaultNetworkTargetingField;
        
        private string descriptiveNameField;
        
        private EmailPromotionsPreferences emailPromotionsPreferencesField;
        
        private string languagePreferenceField;
        
        private Address primaryAddressField;
        
        private string primaryBusinessCategoryField;
        
        private System.Nullable<long> timeZoneEffectiveDateField;
        
        private bool timeZoneEffectiveDateFieldSpecified;
        
        private string timeZoneIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Address billingAddress {
            get {
                return this.billingAddressField;
            }
            set {
                this.billingAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string currencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> customerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool customerIdSpecified {
            get {
                return this.customerIdFieldSpecified;
            }
            set {
                this.customerIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("networkTypes", IsNullable=false)]
        public NetworkType[] defaultNetworkTargeting {
            get {
                return this.defaultNetworkTargetingField;
            }
            set {
                this.defaultNetworkTargetingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string descriptiveName {
            get {
                return this.descriptiveNameField;
            }
            set {
                this.descriptiveNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EmailPromotionsPreferences emailPromotionsPreferences {
            get {
                return this.emailPromotionsPreferencesField;
            }
            set {
                this.emailPromotionsPreferencesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string languagePreference {
            get {
                return this.languagePreferenceField;
            }
            set {
                this.languagePreferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Address primaryAddress {
            get {
                return this.primaryAddressField;
            }
            set {
                this.primaryAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string primaryBusinessCategory {
            get {
                return this.primaryBusinessCategoryField;
            }
            set {
                this.primaryBusinessCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> timeZoneEffectiveDate {
            get {
                return this.timeZoneEffectiveDateField;
            }
            set {
                this.timeZoneEffectiveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeZoneEffectiveDateSpecified {
            get {
                return this.timeZoneEffectiveDateFieldSpecified;
            }
            set {
                this.timeZoneEffectiveDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string timeZoneId {
            get {
                return this.timeZoneIdField;
            }
            set {
                this.timeZoneIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    public partial class Address {
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string cityField;
        
        private string companyNameField;
        
        private string countryCodeField;
        
        private string emailAddressField;
        
        private string faxNumberField;
        
        private string nameField;
        
        private string phoneNumberField;
        
        private string postalCodeField;
        
        private string stateField;
        
        /// <remarks/>
        public string addressLine1 {
            get {
                return this.addressLine1Field;
            }
            set {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string addressLine2 {
            get {
                return this.addressLine2Field;
            }
            set {
                this.addressLine2Field = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string companyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string faxNumber {
            get {
                return this.faxNumberField;
            }
            set {
                this.faxNumberField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    public partial class MccAlert {
        
        private string clientCompanyNameField;
        
        private long clientCustomerIdField;
        
        private string clientLoginField;
        
        private string clientNameField;
        
        private MccAlertPriority priorityField;
        
        private System.DateTime triggerTimeField;
        
        private MccAlertType typeField;
        
        /// <remarks/>
        public string clientCompanyName {
            get {
                return this.clientCompanyNameField;
            }
            set {
                this.clientCompanyNameField = value;
            }
        }
        
        /// <remarks/>
        public long clientCustomerId {
            get {
                return this.clientCustomerIdField;
            }
            set {
                this.clientCustomerIdField = value;
            }
        }
        
        /// <remarks/>
        public string clientLogin {
            get {
                return this.clientLoginField;
            }
            set {
                this.clientLoginField = value;
            }
        }
        
        /// <remarks/>
        public string clientName {
            get {
                return this.clientNameField;
            }
            set {
                this.clientNameField = value;
            }
        }
        
        /// <remarks/>
        public MccAlertPriority priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime triggerTime {
            get {
                return this.triggerTimeField;
            }
            set {
                this.triggerTimeField = value;
            }
        }
        
        /// <remarks/>
        public MccAlertType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    public enum MccAlertPriority {
        
        /// <remarks/>
        Low,
        
        /// <remarks/>
        High,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    public enum MccAlertType {
        
        /// <remarks/>
        AccountOnTarget,
        
        /// <remarks/>
        DeclinedPayment,
        
        /// <remarks/>
        CreditCardExpiring,
        
        /// <remarks/>
        AccountBudgetEnding,
        
        /// <remarks/>
        CampaignEnding,
        
        /// <remarks/>
        CreativeDisapproved,
        
        /// <remarks/>
        PaymentNotEntered,
        
        /// <remarks/>
        MissingBankReferenceNumber,
        
        /// <remarks/>
        CampaignEnded,
        
        /// <remarks/>
        KeywordBelowMinCpc,
        
        /// <remarks/>
        AccountBudgetBurnRate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    public partial class ClientAccountInfo {
        
        private string emailAddressField;
        
        private bool isCustomerManagerField;
        
        /// <remarks/>
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        public bool isCustomerManager {
            get {
                return this.isCustomerManagerField;
            }
            set {
                this.isCustomerManagerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    public partial class EmailPromotionsPreferences {
        
        private bool accountPerformanceEnabledField;
        
        private bool disapprovedAdsEnabledField;
        
        private bool marketResearchEnabledField;
        
        private bool newsletterEnabledField;
        
        private bool promotionsEnabledField;
        
        /// <remarks/>
        public bool accountPerformanceEnabled {
            get {
                return this.accountPerformanceEnabledField;
            }
            set {
                this.accountPerformanceEnabledField = value;
            }
        }
        
        /// <remarks/>
        public bool disapprovedAdsEnabled {
            get {
                return this.disapprovedAdsEnabledField;
            }
            set {
                this.disapprovedAdsEnabledField = value;
            }
        }
        
        /// <remarks/>
        public bool marketResearchEnabled {
            get {
                return this.marketResearchEnabledField;
            }
            set {
                this.marketResearchEnabledField = value;
            }
        }
        
        /// <remarks/>
        public bool newsletterEnabled {
            get {
                return this.newsletterEnabledField;
            }
            set {
                this.newsletterEnabledField = value;
            }
        }
        
        /// <remarks/>
        public bool promotionsEnabled {
            get {
                return this.promotionsEnabledField;
            }
            set {
                this.promotionsEnabledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v13")]
    public enum NetworkType {
        
        /// <remarks/>
        GoogleSearch,
        
        /// <remarks/>
        SearchNetwork,
        
        /// <remarks/>
        ContentNetwork,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getAccountInfoCompletedEventHandler(object sender, getAccountInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAccountInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAccountInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AccountInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AccountInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getClientAccountInfosCompletedEventHandler(object sender, getClientAccountInfosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getClientAccountInfosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getClientAccountInfosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClientAccountInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClientAccountInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getClientAccountsCompletedEventHandler(object sender, getClientAccountsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getClientAccountsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getClientAccountsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getMccAlertsCompletedEventHandler(object sender, getMccAlertsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMccAlertsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMccAlertsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MccAlert[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MccAlert[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void updateAccountInfoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591