//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easynet.Edge.Services.Google.Adwords.GoogleCampaignService {
    using System;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(ElementName="ApiExceptionFault", Namespace="https://adwords.google.com/api/adwords/cm/v200909", IsNullable=false)]
    public partial class ApiException : object, System.Xml.Serialization.IXmlSerializable, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("ApiException", "https://adwords.google.com/api/adwords/cm/v200909");
        
        public System.Xml.XmlNode[] Nodes {
            get {
                return this.nodesField;
            }
            set {
                if ((object.ReferenceEquals(this.nodesField, value) != true)) {
                    this.nodesField = value;
                    this.RaisePropertyChanged("Nodes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        public void ReadXml(System.Xml.XmlReader reader) {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer) {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema() {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas) {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationException", Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    [System.SerializableAttribute()]
    public partial class ApplicationException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationExceptionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ApplicationException.Type", EmitDefaultValue=false, Order=1)]
        public string ApplicationExceptionType {
            get {
                return this.ApplicationExceptionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationExceptionTypeField, value) != true)) {
                    this.ApplicationExceptionTypeField = value;
                    this.RaisePropertyChanged("ApplicationExceptionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909", ConfigurationName="GoogleCampaignService.CampaignServiceInterface")]
    public interface CampaignServiceInterface {
        
        // CODEGEN: Generating message contract since message getRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.ApiException), Action="", Name="ApiExceptionFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListReturnValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Operation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComparableValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Page))]
        Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.getResponse get(Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.getRequest request);
        
        // CODEGEN: Generating message contract since message mutateRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.ApiException), Action="", Name="ApiExceptionFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListReturnValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Operation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComparableValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Page))]
        Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.mutateResponse mutate(Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.mutateRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class SoapHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string applicationTokenField;
        
        private string authTokenField;
        
        private string clientCustomerIdField;
        
        private string clientEmailField;
        
        private string developerTokenField;
        
        private string userAgentField;
        
        private bool validateOnlyField;
        
        private bool validateOnlyFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string applicationToken {
            get {
                return this.applicationTokenField;
            }
            set {
                this.applicationTokenField = value;
                this.RaisePropertyChanged("applicationToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string authToken {
            get {
                return this.authTokenField;
            }
            set {
                this.authTokenField = value;
                this.RaisePropertyChanged("authToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string clientCustomerId {
            get {
                return this.clientCustomerIdField;
            }
            set {
                this.clientCustomerIdField = value;
                this.RaisePropertyChanged("clientCustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string clientEmail {
            get {
                return this.clientEmailField;
            }
            set {
                this.clientEmailField = value;
                this.RaisePropertyChanged("clientEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string developerToken {
            get {
                return this.developerTokenField;
            }
            set {
                this.developerTokenField = value;
                this.RaisePropertyChanged("developerToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string userAgent {
            get {
                return this.userAgentField;
            }
            set {
                this.userAgentField = value;
                this.RaisePropertyChanged("userAgent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool validateOnly {
            get {
                return this.validateOnlyField;
            }
            set {
                this.validateOnlyField = value;
                this.RaisePropertyChanged("validateOnly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validateOnlySpecified {
            get {
                return this.validateOnlyFieldSpecified;
            }
            set {
                this.validateOnlyFieldSpecified = value;
                this.RaisePropertyChanged("validateOnlySpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CampaignReturnValue))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public abstract partial class ListReturnValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string listReturnValueTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ListReturnValue.Type", Order=0)]
        public string ListReturnValueType {
            get {
                return this.listReturnValueTypeField;
            }
            set {
                this.listReturnValueTypeField = value;
                this.RaisePropertyChanged("ListReturnValueType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class CampaignReturnValue : ListReturnValue {
        
        private Campaign[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value", Order=0)]
        public Campaign[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class Campaign : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        private CampaignStatus statusField;
        
        private bool statusFieldSpecified;
        
        private ServingStatus servingStatusField;
        
        private bool servingStatusFieldSpecified;
        
        private string startDateField;
        
        private string endDateField;
        
        private Budget budgetField;
        
        private BiddingStrategy biddingStrategyField;
        
        private AutoKeywordMatchingStatus autoKeywordMatchingStatusField;
        
        private bool autoKeywordMatchingStatusFieldSpecified;
        
        private Stats statsField;
        
        private AdServingOptimizationStatus adServingOptimizationStatusField;
        
        private bool adServingOptimizationStatusFieldSpecified;
        
        private FrequencyCap frequencyCapField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CampaignStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ServingStatus servingStatus {
            get {
                return this.servingStatusField;
            }
            set {
                this.servingStatusField = value;
                this.RaisePropertyChanged("servingStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool servingStatusSpecified {
            get {
                return this.servingStatusFieldSpecified;
            }
            set {
                this.servingStatusFieldSpecified = value;
                this.RaisePropertyChanged("servingStatusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("startDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("endDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Budget budget {
            get {
                return this.budgetField;
            }
            set {
                this.budgetField = value;
                this.RaisePropertyChanged("budget");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public BiddingStrategy biddingStrategy {
            get {
                return this.biddingStrategyField;
            }
            set {
                this.biddingStrategyField = value;
                this.RaisePropertyChanged("biddingStrategy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public AutoKeywordMatchingStatus autoKeywordMatchingStatus {
            get {
                return this.autoKeywordMatchingStatusField;
            }
            set {
                this.autoKeywordMatchingStatusField = value;
                this.RaisePropertyChanged("autoKeywordMatchingStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool autoKeywordMatchingStatusSpecified {
            get {
                return this.autoKeywordMatchingStatusFieldSpecified;
            }
            set {
                this.autoKeywordMatchingStatusFieldSpecified = value;
                this.RaisePropertyChanged("autoKeywordMatchingStatusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public Stats stats {
            get {
                return this.statsField;
            }
            set {
                this.statsField = value;
                this.RaisePropertyChanged("stats");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public AdServingOptimizationStatus adServingOptimizationStatus {
            get {
                return this.adServingOptimizationStatusField;
            }
            set {
                this.adServingOptimizationStatusField = value;
                this.RaisePropertyChanged("adServingOptimizationStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adServingOptimizationStatusSpecified {
            get {
                return this.adServingOptimizationStatusFieldSpecified;
            }
            set {
                this.adServingOptimizationStatusFieldSpecified = value;
                this.RaisePropertyChanged("adServingOptimizationStatusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public FrequencyCap frequencyCap {
            get {
                return this.frequencyCapField;
            }
            set {
                this.frequencyCapField = value;
                this.RaisePropertyChanged("frequencyCap");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public enum CampaignStatus {
        
        /// <remarks/>
        ACTIVE,
        
        /// <remarks/>
        DELETED,
        
        /// <remarks/>
        PAUSED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public enum ServingStatus {
        
        /// <remarks/>
        SERVING,
        
        /// <remarks/>
        NONE,
        
        /// <remarks/>
        ENDED,
        
        /// <remarks/>
        PENDING,
        
        /// <remarks/>
        SUSPENDED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class Budget : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BudgetBudgetPeriod periodField;
        
        private bool periodFieldSpecified;
        
        private Money amountField;
        
        private BudgetBudgetDeliveryMethod deliveryMethodField;
        
        private bool deliveryMethodFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BudgetBudgetPeriod period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
                this.RaisePropertyChanged("period");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodSpecified {
            get {
                return this.periodFieldSpecified;
            }
            set {
                this.periodFieldSpecified = value;
                this.RaisePropertyChanged("periodSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Money amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public BudgetBudgetDeliveryMethod deliveryMethod {
            get {
                return this.deliveryMethodField;
            }
            set {
                this.deliveryMethodField = value;
                this.RaisePropertyChanged("deliveryMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deliveryMethodSpecified {
            get {
                return this.deliveryMethodFieldSpecified;
            }
            set {
                this.deliveryMethodFieldSpecified = value;
                this.RaisePropertyChanged("deliveryMethodSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Budget.BudgetPeriod", Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public enum BudgetBudgetPeriod {
        
        /// <remarks/>
        DAILY,
        
        /// <remarks/>
        MONTHLY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class Money : ComparableValue {
        
        private long microAmountField;
        
        private bool microAmountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long microAmount {
            get {
                return this.microAmountField;
            }
            set {
                this.microAmountField = value;
                this.RaisePropertyChanged("microAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool microAmountSpecified {
            get {
                return this.microAmountFieldSpecified;
            }
            set {
                this.microAmountFieldSpecified = value;
                this.RaisePropertyChanged("microAmountSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NumberValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LongValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoubleValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Money))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public abstract partial class ComparableValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string comparableValueTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ComparableValue.Type", Order=0)]
        public string ComparableValueType {
            get {
                return this.comparableValueTypeField;
            }
            set {
                this.comparableValueTypeField = value;
                this.RaisePropertyChanged("ComparableValueType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LongValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoubleValue))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public abstract partial class NumberValue : ComparableValue {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class LongValue : NumberValue {
        
        private long numberField;
        
        private bool numberFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numberSpecified {
            get {
                return this.numberFieldSpecified;
            }
            set {
                this.numberFieldSpecified = value;
                this.RaisePropertyChanged("numberSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class DoubleValue : NumberValue {
        
        private double numberField;
        
        private bool numberFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numberSpecified {
            get {
                return this.numberFieldSpecified;
            }
            set {
                this.numberFieldSpecified = value;
                this.RaisePropertyChanged("numberSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Budget.BudgetDeliveryMethod", Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public enum BudgetBudgetDeliveryMethod {
        
        /// <remarks/>
        STANDARD,
        
        /// <remarks/>
        ACCELERATED,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BudgetOptimizer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ManualCPM))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ManualCPC))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConversionOptimizer))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public abstract partial class BiddingStrategy : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string biddingStrategyTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BiddingStrategy.Type", Order=0)]
        public string BiddingStrategyType {
            get {
                return this.biddingStrategyTypeField;
            }
            set {
                this.biddingStrategyTypeField = value;
                this.RaisePropertyChanged("BiddingStrategyType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class BudgetOptimizer : BiddingStrategy {
        
        private Money bidCeilingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Money bidCeiling {
            get {
                return this.bidCeilingField;
            }
            set {
                this.bidCeilingField = value;
                this.RaisePropertyChanged("bidCeiling");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class ManualCPM : BiddingStrategy {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class ManualCPC : BiddingStrategy {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class ConversionOptimizer : BiddingStrategy {
        
        private PricingModel pricingModelField;
        
        private bool pricingModelFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PricingModel pricingModel {
            get {
                return this.pricingModelField;
            }
            set {
                this.pricingModelField = value;
                this.RaisePropertyChanged("pricingModel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pricingModelSpecified {
            get {
                return this.pricingModelFieldSpecified;
            }
            set {
                this.pricingModelFieldSpecified = value;
                this.RaisePropertyChanged("pricingModelSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public enum PricingModel {
        
        /// <remarks/>
        CLICKS,
        
        /// <remarks/>
        IMPRESSIONS,
        
        /// <remarks/>
        CONVERSIONS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public enum AutoKeywordMatchingStatus {
        
        /// <remarks/>
        OPT_IN,
        
        /// <remarks/>
        OPT_OUT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class Stats : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string startDateField;
        
        private string endDateField;
        
        private StatsNetwork networkField;
        
        private bool networkFieldSpecified;
        
        private long clicksField;
        
        private bool clicksFieldSpecified;
        
        private long impressionsField;
        
        private bool impressionsFieldSpecified;
        
        private Money costField;
        
        private double averagePositionField;
        
        private bool averagePositionFieldSpecified;
        
        private Money averageCpcField;
        
        private Money averageCpmField;
        
        private double ctrField;
        
        private bool ctrFieldSpecified;
        
        private long conversionsField;
        
        private bool conversionsFieldSpecified;
        
        private double conversionRateField;
        
        private bool conversionRateFieldSpecified;
        
        private Money costPerConversionField;
        
        private long conversionsManyPerClickField;
        
        private bool conversionsManyPerClickFieldSpecified;
        
        private double conversionRateManyPerClickField;
        
        private bool conversionRateManyPerClickFieldSpecified;
        
        private Money costPerConversionManyPerClickField;
        
        private string statsTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("startDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("endDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public StatsNetwork network {
            get {
                return this.networkField;
            }
            set {
                this.networkField = value;
                this.RaisePropertyChanged("network");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool networkSpecified {
            get {
                return this.networkFieldSpecified;
            }
            set {
                this.networkFieldSpecified = value;
                this.RaisePropertyChanged("networkSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long clicks {
            get {
                return this.clicksField;
            }
            set {
                this.clicksField = value;
                this.RaisePropertyChanged("clicks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clicksSpecified {
            get {
                return this.clicksFieldSpecified;
            }
            set {
                this.clicksFieldSpecified = value;
                this.RaisePropertyChanged("clicksSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long impressions {
            get {
                return this.impressionsField;
            }
            set {
                this.impressionsField = value;
                this.RaisePropertyChanged("impressions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool impressionsSpecified {
            get {
                return this.impressionsFieldSpecified;
            }
            set {
                this.impressionsFieldSpecified = value;
                this.RaisePropertyChanged("impressionsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Money cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
                this.RaisePropertyChanged("cost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double averagePosition {
            get {
                return this.averagePositionField;
            }
            set {
                this.averagePositionField = value;
                this.RaisePropertyChanged("averagePosition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool averagePositionSpecified {
            get {
                return this.averagePositionFieldSpecified;
            }
            set {
                this.averagePositionFieldSpecified = value;
                this.RaisePropertyChanged("averagePositionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Money averageCpc {
            get {
                return this.averageCpcField;
            }
            set {
                this.averageCpcField = value;
                this.RaisePropertyChanged("averageCpc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Money averageCpm {
            get {
                return this.averageCpmField;
            }
            set {
                this.averageCpmField = value;
                this.RaisePropertyChanged("averageCpm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public double ctr {
            get {
                return this.ctrField;
            }
            set {
                this.ctrField = value;
                this.RaisePropertyChanged("ctr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ctrSpecified {
            get {
                return this.ctrFieldSpecified;
            }
            set {
                this.ctrFieldSpecified = value;
                this.RaisePropertyChanged("ctrSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public long conversions {
            get {
                return this.conversionsField;
            }
            set {
                this.conversionsField = value;
                this.RaisePropertyChanged("conversions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool conversionsSpecified {
            get {
                return this.conversionsFieldSpecified;
            }
            set {
                this.conversionsFieldSpecified = value;
                this.RaisePropertyChanged("conversionsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public double conversionRate {
            get {
                return this.conversionRateField;
            }
            set {
                this.conversionRateField = value;
                this.RaisePropertyChanged("conversionRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool conversionRateSpecified {
            get {
                return this.conversionRateFieldSpecified;
            }
            set {
                this.conversionRateFieldSpecified = value;
                this.RaisePropertyChanged("conversionRateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public Money costPerConversion {
            get {
                return this.costPerConversionField;
            }
            set {
                this.costPerConversionField = value;
                this.RaisePropertyChanged("costPerConversion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public long conversionsManyPerClick {
            get {
                return this.conversionsManyPerClickField;
            }
            set {
                this.conversionsManyPerClickField = value;
                this.RaisePropertyChanged("conversionsManyPerClick");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool conversionsManyPerClickSpecified {
            get {
                return this.conversionsManyPerClickFieldSpecified;
            }
            set {
                this.conversionsManyPerClickFieldSpecified = value;
                this.RaisePropertyChanged("conversionsManyPerClickSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public double conversionRateManyPerClick {
            get {
                return this.conversionRateManyPerClickField;
            }
            set {
                this.conversionRateManyPerClickField = value;
                this.RaisePropertyChanged("conversionRateManyPerClick");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool conversionRateManyPerClickSpecified {
            get {
                return this.conversionRateManyPerClickFieldSpecified;
            }
            set {
                this.conversionRateManyPerClickFieldSpecified = value;
                this.RaisePropertyChanged("conversionRateManyPerClickSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public Money costPerConversionManyPerClick {
            get {
                return this.costPerConversionManyPerClickField;
            }
            set {
                this.costPerConversionManyPerClickField = value;
                this.RaisePropertyChanged("costPerConversionManyPerClick");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stats.Type", Order=16)]
        public string StatsType {
            get {
                return this.statsTypeField;
            }
            set {
                this.statsTypeField = value;
                this.RaisePropertyChanged("StatsType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Stats.Network", Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public enum StatsNetwork {
        
        /// <remarks/>
        SEARCH,
        
        /// <remarks/>
        GOOGLE_SEARCH,
        
        /// <remarks/>
        SEARCH_NETWORK,
        
        /// <remarks/>
        CONTENT,
        
        /// <remarks/>
        CONTENT_KEYWORD_BID,
        
        /// <remarks/>
        CONTENT_PLACEMENT_BID,
        
        /// <remarks/>
        ALL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public enum AdServingOptimizationStatus {
        
        /// <remarks/>
        OPTIMIZE,
        
        /// <remarks/>
        ROTATE,
        
        /// <remarks/>
        UNAVAILABLE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class FrequencyCap : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long impressionsField;
        
        private bool impressionsFieldSpecified;
        
        private TimeUnit timeUnitField;
        
        private bool timeUnitFieldSpecified;
        
        private Level levelField;
        
        private bool levelFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long impressions {
            get {
                return this.impressionsField;
            }
            set {
                this.impressionsField = value;
                this.RaisePropertyChanged("impressions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool impressionsSpecified {
            get {
                return this.impressionsFieldSpecified;
            }
            set {
                this.impressionsFieldSpecified = value;
                this.RaisePropertyChanged("impressionsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TimeUnit timeUnit {
            get {
                return this.timeUnitField;
            }
            set {
                this.timeUnitField = value;
                this.RaisePropertyChanged("timeUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeUnitSpecified {
            get {
                return this.timeUnitFieldSpecified;
            }
            set {
                this.timeUnitFieldSpecified = value;
                this.RaisePropertyChanged("timeUnitSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Level level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
                this.RaisePropertyChanged("level");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool levelSpecified {
            get {
                return this.levelFieldSpecified;
            }
            set {
                this.levelFieldSpecified = value;
                this.RaisePropertyChanged("levelSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public enum TimeUnit {
        
        /// <remarks/>
        MINUTE,
        
        /// <remarks/>
        HOUR,
        
        /// <remarks/>
        DAY,
        
        /// <remarks/>
        WEEK,
        
        /// <remarks/>
        MONTH,
        
        /// <remarks/>
        LIFETIME,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public enum Level {
        
        /// <remarks/>
        CREATIVE,
        
        /// <remarks/>
        ADGROUP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class Bid : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Money amountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Money amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ManualCPMAdGroupBids))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ManualCPCAdGroupBids))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConversionOptimizerAdGroupBids))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BudgetOptimizerAdGroupBids))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public abstract partial class AdGroupBids : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string adGroupBidsTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdGroupBids.Type", Order=0)]
        public string AdGroupBidsType {
            get {
                return this.adGroupBidsTypeField;
            }
            set {
                this.adGroupBidsTypeField = value;
                this.RaisePropertyChanged("AdGroupBidsType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class ManualCPMAdGroupBids : AdGroupBids {
        
        private Bid maxCpmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Bid maxCpm {
            get {
                return this.maxCpmField;
            }
            set {
                this.maxCpmField = value;
                this.RaisePropertyChanged("maxCpm");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class ManualCPCAdGroupBids : AdGroupBids {
        
        private Bid keywordMaxCpcField;
        
        private Bid keywordContentMaxCpcField;
        
        private Bid siteMaxCpcField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Bid keywordMaxCpc {
            get {
                return this.keywordMaxCpcField;
            }
            set {
                this.keywordMaxCpcField = value;
                this.RaisePropertyChanged("keywordMaxCpc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Bid keywordContentMaxCpc {
            get {
                return this.keywordContentMaxCpcField;
            }
            set {
                this.keywordContentMaxCpcField = value;
                this.RaisePropertyChanged("keywordContentMaxCpc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Bid siteMaxCpc {
            get {
                return this.siteMaxCpcField;
            }
            set {
                this.siteMaxCpcField = value;
                this.RaisePropertyChanged("siteMaxCpc");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class ConversionOptimizerAdGroupBids : AdGroupBids {
        
        private Bid targetCpaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Bid targetCpa {
            get {
                return this.targetCpaField;
            }
            set {
                this.targetCpaField = value;
                this.RaisePropertyChanged("targetCpa");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class BudgetOptimizerAdGroupBids : AdGroupBids {
        
        private Bid proxyKeywordMaxCpcField;
        
        private Bid proxySiteMaxCpcField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Bid proxyKeywordMaxCpc {
            get {
                return this.proxyKeywordMaxCpcField;
            }
            set {
                this.proxyKeywordMaxCpcField = value;
                this.RaisePropertyChanged("proxyKeywordMaxCpc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Bid proxySiteMaxCpc {
            get {
                return this.proxySiteMaxCpcField;
            }
            set {
                this.proxySiteMaxCpcField = value;
                this.RaisePropertyChanged("proxySiteMaxCpc");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConversionOptimizerBiddingTransition))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class BiddingTransition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BiddingStrategy targetBiddingStrategyField;
        
        private AdGroupBids explicitAdGroupBidsField;
        
        private string biddingTransitionTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BiddingStrategy targetBiddingStrategy {
            get {
                return this.targetBiddingStrategyField;
            }
            set {
                this.targetBiddingStrategyField = value;
                this.RaisePropertyChanged("targetBiddingStrategy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AdGroupBids explicitAdGroupBids {
            get {
                return this.explicitAdGroupBidsField;
            }
            set {
                this.explicitAdGroupBidsField = value;
                this.RaisePropertyChanged("explicitAdGroupBids");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BiddingTransition.Type", Order=2)]
        public string BiddingTransitionType {
            get {
                return this.biddingTransitionTypeField;
            }
            set {
                this.biddingTransitionTypeField = value;
                this.RaisePropertyChanged("BiddingTransitionType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class ConversionOptimizerBiddingTransition : BiddingTransition {
        
        private bool useSavedBidsField;
        
        private bool useSavedBidsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool useSavedBids {
            get {
                return this.useSavedBidsField;
            }
            set {
                this.useSavedBidsField = value;
                this.RaisePropertyChanged("useSavedBids");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool useSavedBidsSpecified {
            get {
                return this.useSavedBidsFieldSpecified;
            }
            set {
                this.useSavedBidsFieldSpecified = value;
                this.RaisePropertyChanged("useSavedBidsSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CampaignOperation))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public abstract partial class Operation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Operator operatorField;
        
        private bool operatorFieldSpecified;
        
        private string operationTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Operator @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("operator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operatorSpecified {
            get {
                return this.operatorFieldSpecified;
            }
            set {
                this.operatorFieldSpecified = value;
                this.RaisePropertyChanged("operatorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Operation.Type", Order=1)]
        public string OperationType {
            get {
                return this.operationTypeField;
            }
            set {
                this.operationTypeField = value;
                this.RaisePropertyChanged("OperationType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public enum Operator {
        
        /// <remarks/>
        ADD,
        
        /// <remarks/>
        REMOVE,
        
        /// <remarks/>
        SET,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class CampaignOperation : Operation {
        
        private BiddingTransition biddingTransitionField;
        
        private Campaign operandField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BiddingTransition biddingTransition {
            get {
                return this.biddingTransitionField;
            }
            set {
                this.biddingTransitionField = value;
                this.RaisePropertyChanged("biddingTransition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Campaign operand {
            get {
                return this.operandField;
            }
            set {
                this.operandField = value;
                this.RaisePropertyChanged("operand");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class SoapResponseHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestIdField;
        
        private long operationsField;
        
        private bool operationsFieldSpecified;
        
        private long responseTimeField;
        
        private bool responseTimeFieldSpecified;
        
        private long unitsField;
        
        private bool unitsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("requestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long operations {
            get {
                return this.operationsField;
            }
            set {
                this.operationsField = value;
                this.RaisePropertyChanged("operations");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operationsSpecified {
            get {
                return this.operationsFieldSpecified;
            }
            set {
                this.operationsFieldSpecified = value;
                this.RaisePropertyChanged("operationsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long responseTime {
            get {
                return this.responseTimeField;
            }
            set {
                this.responseTimeField = value;
                this.RaisePropertyChanged("responseTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool responseTimeSpecified {
            get {
                return this.responseTimeFieldSpecified;
            }
            set {
                this.responseTimeFieldSpecified = value;
                this.RaisePropertyChanged("responseTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
                this.RaisePropertyChanged("units");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unitsSpecified {
            get {
                return this.unitsFieldSpecified;
            }
            set {
                this.unitsFieldSpecified = value;
                this.RaisePropertyChanged("unitsSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CampaignPage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public abstract partial class Page : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int totalNumEntriesField;
        
        private bool totalNumEntriesFieldSpecified;
        
        private string pageTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int totalNumEntries {
            get {
                return this.totalNumEntriesField;
            }
            set {
                this.totalNumEntriesField = value;
                this.RaisePropertyChanged("totalNumEntries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalNumEntriesSpecified {
            get {
                return this.totalNumEntriesFieldSpecified;
            }
            set {
                this.totalNumEntriesFieldSpecified = value;
                this.RaisePropertyChanged("totalNumEntriesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Page.Type", Order=1)]
        public string PageType {
            get {
                return this.pageTypeField;
            }
            set {
                this.pageTypeField = value;
                this.RaisePropertyChanged("PageType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class CampaignPage : Page {
        
        private Budget totalBudgetField;
        
        private Campaign[] entriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Budget totalBudget {
            get {
                return this.totalBudgetField;
            }
            set {
                this.totalBudgetField = value;
                this.RaisePropertyChanged("totalBudget");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entries", Order=1)]
        public Campaign[] entries {
            get {
                return this.entriesField;
            }
            set {
                this.entriesField = value;
                this.RaisePropertyChanged("entries");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class Paging : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int startIndexField;
        
        private bool startIndexFieldSpecified;
        
        private int numberResultsField;
        
        private bool numberResultsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int startIndex {
            get {
                return this.startIndexField;
            }
            set {
                this.startIndexField = value;
                this.RaisePropertyChanged("startIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startIndexSpecified {
            get {
                return this.startIndexFieldSpecified;
            }
            set {
                this.startIndexFieldSpecified = value;
                this.RaisePropertyChanged("startIndexSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int numberResults {
            get {
                return this.numberResultsField;
            }
            set {
                this.numberResultsField = value;
                this.RaisePropertyChanged("numberResults");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numberResultsSpecified {
            get {
                return this.numberResultsFieldSpecified;
            }
            set {
                this.numberResultsFieldSpecified = value;
                this.RaisePropertyChanged("numberResultsSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class DateRange : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string minField;
        
        private string maxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string min {
            get {
                return this.minField;
            }
            set {
                this.minField = value;
                this.RaisePropertyChanged("min");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string max {
            get {
                return this.maxField;
            }
            set {
                this.maxField = value;
                this.RaisePropertyChanged("max");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class StatsSelector : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DateRange dateRangeField;
        
        private string statsSelectorTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DateRange dateRange {
            get {
                return this.dateRangeField;
            }
            set {
                this.dateRangeField = value;
                this.RaisePropertyChanged("dateRange");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StatsSelector.Type", Order=1)]
        public string StatsSelectorType {
            get {
                return this.statsSelectorTypeField;
            }
            set {
                this.statsSelectorTypeField = value;
                this.RaisePropertyChanged("StatsSelectorType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class CampaignSelector : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long[] idsField;
        
        private CampaignStatus[] campaignStatusesField;
        
        private StatsSelector statsSelectorField;
        
        private Paging pagingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ids", Order=0)]
        public long[] ids {
            get {
                return this.idsField;
            }
            set {
                this.idsField = value;
                this.RaisePropertyChanged("ids");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("campaignStatuses", Order=1)]
        public CampaignStatus[] campaignStatuses {
            get {
                return this.campaignStatusesField;
            }
            set {
                this.campaignStatusesField = value;
                this.RaisePropertyChanged("campaignStatuses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public StatsSelector statsSelector {
            get {
                return this.statsSelectorField;
            }
            set {
                this.statsSelectorField = value;
                this.RaisePropertyChanged("statsSelector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Paging paging {
            get {
                return this.pagingField;
            }
            set {
                this.pagingField = value;
                this.RaisePropertyChanged("paging");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get", WrapperNamespace="https://adwords.google.com/api/adwords/cm/v200909", IsWrapped=true)]
    public partial class getRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
        public Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.SoapHeader RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909", Order=0)]
        public Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.CampaignSelector selector;
        
        public getRequest() {
        }
        
        public getRequest(Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.SoapHeader RequestHeader, Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.CampaignSelector selector) {
            this.RequestHeader = RequestHeader;
            this.selector = selector;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResponse", WrapperNamespace="https://adwords.google.com/api/adwords/cm/v200909", IsWrapped=true)]
    public partial class getResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
        public Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.SoapResponseHeader ResponseHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909", Order=0)]
        public Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.CampaignPage rval;
        
        public getResponse() {
        }
        
        public getResponse(Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.SoapResponseHeader ResponseHeader, Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.CampaignPage rval) {
            this.ResponseHeader = ResponseHeader;
            this.rval = rval;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mutate", WrapperNamespace="https://adwords.google.com/api/adwords/cm/v200909", IsWrapped=true)]
    public partial class mutateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
        public Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.SoapHeader RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("operations")]
        public CampaignOperation[] operations;
        
        public mutateRequest() {
        }
        
        public mutateRequest(Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.SoapHeader RequestHeader, CampaignOperation[] operations) {
            this.RequestHeader = RequestHeader;
            this.operations = operations;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mutateResponse", WrapperNamespace="https://adwords.google.com/api/adwords/cm/v200909", IsWrapped=true)]
    public partial class mutateResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
        public Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.SoapResponseHeader ResponseHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909", Order=0)]
        public Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.CampaignReturnValue rval;
        
        public mutateResponse() {
        }
        
        public mutateResponse(Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.SoapResponseHeader ResponseHeader, Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.CampaignReturnValue rval) {
            this.ResponseHeader = ResponseHeader;
            this.rval = rval;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface CampaignServiceInterfaceChannel : Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.CampaignServiceInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CampaignServiceInterfaceClient : System.ServiceModel.ClientBase<Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.CampaignServiceInterface>, Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.CampaignServiceInterface {
        
        public CampaignServiceInterfaceClient() {
        }
        
        public CampaignServiceInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CampaignServiceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CampaignServiceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CampaignServiceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.getResponse Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.CampaignServiceInterface.get(Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.getRequest request) {
            return base.Channel.get(request);
        }
        
        public Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.SoapResponseHeader get(Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.SoapHeader RequestHeader, Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.CampaignSelector selector, out Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.CampaignPage rval) {
            Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.getRequest inValue = new Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.getRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.selector = selector;
            Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.getResponse retVal = ((Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.CampaignServiceInterface)(this)).get(inValue);
            rval = retVal.rval;
            return retVal.ResponseHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.mutateResponse Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.CampaignServiceInterface.mutate(Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.mutateRequest request) {
            return base.Channel.mutate(request);
        }
        
        public Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.SoapResponseHeader mutate(Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.SoapHeader RequestHeader, CampaignOperation[] operations, out Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.CampaignReturnValue rval) {
            Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.mutateRequest inValue = new Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.mutateRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.operations = operations;
            Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.mutateResponse retVal = ((Easynet.Edge.Services.Google.Adwords.GoogleCampaignService.CampaignServiceInterface)(this)).mutate(inValue);
            rval = retVal.rval;
            return retVal.ResponseHeader;
        }
    }
}
