//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewRestApiTester.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/bulkupload")]
        public string RemoteAdress {
            get {
                return ((string)(this["RemoteAdress"]));
            }
            set {
                this["RemoteAdress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"OperationType\":\"New\",\"email\":\"amir@seperia.com\",\"Password\":\"123456\",\r\n\"UserID\":" +
            "\"8\",\"Session\":\"0EB3BAD4D3FB3F64FE2EE9EC27B54752\"}")]
        public string BodyLogInJson {
            get {
                return ((string)(this["BodyLogInJson"]));
            }
            set {
                this["BodyLogInJson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("x-edgebi-session:{0}")]
        public string DefaultHeaders {
            get {
                return ((string)(this["DefaultHeaders"]));
            }
            set {
                this["DefaultHeaders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"AccountID\":\"7\",\"Path\":\"management\"}")]
        public string BodyGetSpecificPermission {
            get {
                return ((string)(this["BodyGetSpecificPermission"]));
            }
            set {
                this["BodyGetSpecificPermission"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("test,createfile")]
        public string Services {
            get {
                return ((string)(this["Services"]));
            }
            set {
                this["Services"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8081")]
        public string LocalAdress {
            get {
                return ((string)(this["LocalAdress"]));
            }
            set {
                this["LocalAdress"] = value;
            }
        }
    }
}
