//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12 {
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(ElementName="fault", Namespace="https://adwords.google.com/api/adwords/v12", IsNullable=false)]
    public partial class ApiException : object, System.Xml.Serialization.IXmlSerializable, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("ApiException", "https://adwords.google.com/api/adwords/v12");
        
        public System.Xml.XmlNode[] Nodes {
            get {
                return this.nodesField;
            }
            set {
                if ((object.ReferenceEquals(this.nodesField, value) != true)) {
                    this.nodesField = value;
                    this.RaisePropertyChanged("Nodes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        public void ReadXml(System.Xml.XmlReader reader) {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer) {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema() {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas) {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://adwords.google.com/api/adwords/v12", ConfigurationName="GAdWordsAccountServiceV12.AccountInterface")]
    public interface AccountInterface {
        
        // CODEGEN: Generating message contract since message getAccountInfoRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.ApiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.getAccountInfoResponse getAccountInfo(Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.getAccountInfoRequest request);
        
        // CODEGEN: Generating message contract since message getClientAccountsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.ApiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.getClientAccountsResponse getClientAccounts(Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.getClientAccountsRequest request);
        
        // CODEGEN: Generating message contract since message updateAccountInfoRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.ApiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.updateAccountInfoResponse updateAccountInfo(Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.updateAccountInfoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
    public partial class AccountInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Address billingAddressField;
        
        private string currencyCodeField;
        
        private System.Nullable<long> customerIdField;
        
        private bool customerIdFieldSpecified;
        
        private NetworkType[] defaultNetworkTargetingField;
        
        private string descriptiveNameField;
        
        private EmailPromotionsPreferences emailPromotionsPreferencesField;
        
        private string languagePreferenceField;
        
        private Address primaryAddressField;
        
        private string primaryBusinessCategoryField;
        
        private System.Nullable<long> timeZoneEffectiveDateField;
        
        private bool timeZoneEffectiveDateFieldSpecified;
        
        private string timeZoneIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public Address billingAddress {
            get {
                return this.billingAddressField;
            }
            set {
                this.billingAddressField = value;
                this.RaisePropertyChanged("billingAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string currencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
                this.RaisePropertyChanged("currencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> customerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("customerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool customerIdSpecified {
            get {
                return this.customerIdFieldSpecified;
            }
            set {
                this.customerIdFieldSpecified = value;
                this.RaisePropertyChanged("customerIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("networkTypes", IsNullable=false)]
        public NetworkType[] defaultNetworkTargeting {
            get {
                return this.defaultNetworkTargetingField;
            }
            set {
                this.defaultNetworkTargetingField = value;
                this.RaisePropertyChanged("defaultNetworkTargeting");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string descriptiveName {
            get {
                return this.descriptiveNameField;
            }
            set {
                this.descriptiveNameField = value;
                this.RaisePropertyChanged("descriptiveName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public EmailPromotionsPreferences emailPromotionsPreferences {
            get {
                return this.emailPromotionsPreferencesField;
            }
            set {
                this.emailPromotionsPreferencesField = value;
                this.RaisePropertyChanged("emailPromotionsPreferences");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string languagePreference {
            get {
                return this.languagePreferenceField;
            }
            set {
                this.languagePreferenceField = value;
                this.RaisePropertyChanged("languagePreference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public Address primaryAddress {
            get {
                return this.primaryAddressField;
            }
            set {
                this.primaryAddressField = value;
                this.RaisePropertyChanged("primaryAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string primaryBusinessCategory {
            get {
                return this.primaryBusinessCategoryField;
            }
            set {
                this.primaryBusinessCategoryField = value;
                this.RaisePropertyChanged("primaryBusinessCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<long> timeZoneEffectiveDate {
            get {
                return this.timeZoneEffectiveDateField;
            }
            set {
                this.timeZoneEffectiveDateField = value;
                this.RaisePropertyChanged("timeZoneEffectiveDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeZoneEffectiveDateSpecified {
            get {
                return this.timeZoneEffectiveDateFieldSpecified;
            }
            set {
                this.timeZoneEffectiveDateFieldSpecified = value;
                this.RaisePropertyChanged("timeZoneEffectiveDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string timeZoneId {
            get {
                return this.timeZoneIdField;
            }
            set {
                this.timeZoneIdField = value;
                this.RaisePropertyChanged("timeZoneId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string cityField;
        
        private string companyNameField;
        
        private string countryCodeField;
        
        private string emailAddressField;
        
        private string faxNumberField;
        
        private string nameField;
        
        private string phoneNumberField;
        
        private string postalCodeField;
        
        private string stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string addressLine1 {
            get {
                return this.addressLine1Field;
            }
            set {
                this.addressLine1Field = value;
                this.RaisePropertyChanged("addressLine1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string addressLine2 {
            get {
                return this.addressLine2Field;
            }
            set {
                this.addressLine2Field = value;
                this.RaisePropertyChanged("addressLine2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string companyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
                this.RaisePropertyChanged("companyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("countryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("emailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string faxNumber {
            get {
                return this.faxNumberField;
            }
            set {
                this.faxNumberField = value;
                this.RaisePropertyChanged("faxNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("phoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("postalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
    public partial class EmailPromotionsPreferences : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool accountPerformanceEnabledField;
        
        private bool disapprovedAdsEnabledField;
        
        private bool marketResearchEnabledField;
        
        private bool newsletterEnabledField;
        
        private bool promotionsEnabledField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool accountPerformanceEnabled {
            get {
                return this.accountPerformanceEnabledField;
            }
            set {
                this.accountPerformanceEnabledField = value;
                this.RaisePropertyChanged("accountPerformanceEnabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool disapprovedAdsEnabled {
            get {
                return this.disapprovedAdsEnabledField;
            }
            set {
                this.disapprovedAdsEnabledField = value;
                this.RaisePropertyChanged("disapprovedAdsEnabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool marketResearchEnabled {
            get {
                return this.marketResearchEnabledField;
            }
            set {
                this.marketResearchEnabledField = value;
                this.RaisePropertyChanged("marketResearchEnabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool newsletterEnabled {
            get {
                return this.newsletterEnabledField;
            }
            set {
                this.newsletterEnabledField = value;
                this.RaisePropertyChanged("newsletterEnabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool promotionsEnabled {
            get {
                return this.promotionsEnabledField;
            }
            set {
                this.promotionsEnabledField = value;
                this.RaisePropertyChanged("promotionsEnabled");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
    public enum NetworkType {
        
        /// <remarks/>
        GoogleSearch,
        
        /// <remarks/>
        SearchNetwork,
        
        /// <remarks/>
        ContentNetwork,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccountInfo", WrapperNamespace="https://adwords.google.com/api/adwords/v12", IsWrapped=true)]
    public partial class getAccountInfoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public string useragent;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public string password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public string email;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public string clientEmail;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public string clientCustomerId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public string developerToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public string applicationToken;
        
        public getAccountInfoRequest() {
        }
        
        public getAccountInfoRequest(string useragent, string password, string email, string clientEmail, string clientCustomerId, string developerToken, string applicationToken) {
            this.useragent = useragent;
            this.password = password;
            this.email = email;
            this.clientEmail = clientEmail;
            this.clientCustomerId = clientCustomerId;
            this.developerToken = developerToken;
            this.applicationToken = applicationToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccountInfoResponse", WrapperNamespace="https://adwords.google.com/api/adwords/v12", IsWrapped=true)]
    public partial class getAccountInfoResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public long responseTime;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public long operations;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public long units;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public string requestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://adwords.google.com/api/adwords/v12", Order=0)]
        public Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.AccountInfo getAccountInfoReturn;
        
        public getAccountInfoResponse() {
        }
        
        public getAccountInfoResponse(long responseTime, long operations, long units, string requestId, Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.AccountInfo getAccountInfoReturn) {
            this.responseTime = responseTime;
            this.operations = operations;
            this.units = units;
            this.requestId = requestId;
            this.getAccountInfoReturn = getAccountInfoReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClientAccounts", WrapperNamespace="https://adwords.google.com/api/adwords/v12", IsWrapped=true)]
    public partial class getClientAccountsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public string useragent;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public string password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public string email;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public string clientEmail;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public string clientCustomerId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public string developerToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public string applicationToken;
        
        public getClientAccountsRequest() {
        }
        
        public getClientAccountsRequest(string useragent, string password, string email, string clientEmail, string clientCustomerId, string developerToken, string applicationToken) {
            this.useragent = useragent;
            this.password = password;
            this.email = email;
            this.clientEmail = clientEmail;
            this.clientCustomerId = clientCustomerId;
            this.developerToken = developerToken;
            this.applicationToken = applicationToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClientAccountsResponse", WrapperNamespace="https://adwords.google.com/api/adwords/v12", IsWrapped=true)]
    public partial class getClientAccountsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public long responseTime;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public long operations;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public long units;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public string requestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://adwords.google.com/api/adwords/v12", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getClientAccountsReturn")]
        public string[] getClientAccountsReturn;
        
        public getClientAccountsResponse() {
        }
        
        public getClientAccountsResponse(long responseTime, long operations, long units, string requestId, string[] getClientAccountsReturn) {
            this.responseTime = responseTime;
            this.operations = operations;
            this.units = units;
            this.requestId = requestId;
            this.getClientAccountsReturn = getClientAccountsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateAccountInfo", WrapperNamespace="https://adwords.google.com/api/adwords/v12", IsWrapped=true)]
    public partial class updateAccountInfoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public string useragent;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public string password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public string email;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public string clientEmail;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public string clientCustomerId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public string developerToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public string applicationToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://adwords.google.com/api/adwords/v12", Order=0)]
        public Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.AccountInfo accountInfo;
        
        public updateAccountInfoRequest() {
        }
        
        public updateAccountInfoRequest(string useragent, string password, string email, string clientEmail, string clientCustomerId, string developerToken, string applicationToken, Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.AccountInfo accountInfo) {
            this.useragent = useragent;
            this.password = password;
            this.email = email;
            this.clientEmail = clientEmail;
            this.clientCustomerId = clientCustomerId;
            this.developerToken = developerToken;
            this.applicationToken = applicationToken;
            this.accountInfo = accountInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateAccountInfoResponse", WrapperNamespace="https://adwords.google.com/api/adwords/v12", IsWrapped=true)]
    public partial class updateAccountInfoResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public long responseTime;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public long operations;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public long units;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/v12")]
        public string requestId;
        
        public updateAccountInfoResponse() {
        }
        
        public updateAccountInfoResponse(long responseTime, long operations, long units, string requestId) {
            this.responseTime = responseTime;
            this.operations = operations;
            this.units = units;
            this.requestId = requestId;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface AccountInterfaceChannel : Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.AccountInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AccountInterfaceClient : System.ServiceModel.ClientBase<Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.AccountInterface>, Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.AccountInterface {
        
        public AccountInterfaceClient() {
        }
        
        public AccountInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.getAccountInfoResponse Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.AccountInterface.getAccountInfo(Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.getAccountInfoRequest request) {
            return base.Channel.getAccountInfo(request);
        }
        
        public long getAccountInfo(string useragent, string password, string email, string clientEmail, string clientCustomerId, string developerToken, string applicationToken, out long operations, out long units, out string requestId, out Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.AccountInfo getAccountInfoReturn) {
            Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.getAccountInfoRequest inValue = new Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.getAccountInfoRequest();
            inValue.useragent = useragent;
            inValue.password = password;
            inValue.email = email;
            inValue.clientEmail = clientEmail;
            inValue.clientCustomerId = clientCustomerId;
            inValue.developerToken = developerToken;
            inValue.applicationToken = applicationToken;
            Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.getAccountInfoResponse retVal = ((Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.AccountInterface)(this)).getAccountInfo(inValue);
            operations = retVal.operations;
            units = retVal.units;
            requestId = retVal.requestId;
            getAccountInfoReturn = retVal.getAccountInfoReturn;
            return retVal.responseTime;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.getClientAccountsResponse Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.AccountInterface.getClientAccounts(Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.getClientAccountsRequest request) {
            return base.Channel.getClientAccounts(request);
        }
        
        public long getClientAccounts(string useragent, string password, string email, string clientEmail, string clientCustomerId, string developerToken, string applicationToken, out long operations, out long units, out string requestId, out string[] getClientAccountsReturn) {
            Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.getClientAccountsRequest inValue = new Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.getClientAccountsRequest();
            inValue.useragent = useragent;
            inValue.password = password;
            inValue.email = email;
            inValue.clientEmail = clientEmail;
            inValue.clientCustomerId = clientCustomerId;
            inValue.developerToken = developerToken;
            inValue.applicationToken = applicationToken;
            Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.getClientAccountsResponse retVal = ((Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.AccountInterface)(this)).getClientAccounts(inValue);
            operations = retVal.operations;
            units = retVal.units;
            requestId = retVal.requestId;
            getClientAccountsReturn = retVal.getClientAccountsReturn;
            return retVal.responseTime;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.updateAccountInfoResponse Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.AccountInterface.updateAccountInfo(Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.updateAccountInfoRequest request) {
            return base.Channel.updateAccountInfo(request);
        }
        
        public long updateAccountInfo(string useragent, string password, string email, string clientEmail, string clientCustomerId, string developerToken, string applicationToken, Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.AccountInfo accountInfo, out long operations, out long units, out string requestId) {
            Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.updateAccountInfoRequest inValue = new Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.updateAccountInfoRequest();
            inValue.useragent = useragent;
            inValue.password = password;
            inValue.email = email;
            inValue.clientEmail = clientEmail;
            inValue.clientCustomerId = clientCustomerId;
            inValue.developerToken = developerToken;
            inValue.applicationToken = applicationToken;
            inValue.accountInfo = accountInfo;
            Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.updateAccountInfoResponse retVal = ((Easynet.Edge.Services.Google.Adwords.GAdWordsAccountServiceV12.AccountInterface)(this)).updateAccountInfo(inValue);
            operations = retVal.operations;
            units = retVal.units;
            requestId = retVal.requestId;
            return retVal.responseTime;
        }
    }
}
