//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3603.
// 
#pragma warning disable 1591

namespace Easynet.Edge.Services.Google.Adwords.com.google.adwords {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CampaignServiceSoapBinding", Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListReturnValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Operation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComparableValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Page))]
    public partial class CampaignService : System.Web.Services.Protocols.SoapHttpClientProtocol {

        private MySoapHeader requestHeaderField;
        
        private MySoapResponseHeader responseHeaderField;
        
        private System.Threading.SendOrPostCallback getOperationCompleted;
        
        private System.Threading.SendOrPostCallback mutateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CampaignService() {
            this.Url = global::Easynet.Edge.Services.Google.Adwords.Properties.Settings.Default.Edge_Services_Google_Adwords_com_google_adwords_CampaignService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        public MySoapHeader RequestHeader
        {
            get {
                return this.requestHeaderField;
            }
            set {
                this.requestHeaderField = value;
            }
        }
        
        public MySoapResponseHeader ResponseHeader {
            get {
                return this.responseHeaderField;
            }
            set {
                this.responseHeaderField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getCompletedEventHandler getCompleted;
        
        /// <remarks/>
        public event mutateCompletedEventHandler mutateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeader")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeader", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="https://adwords.google.com/api/adwords/cm/v200909", ResponseNamespace="https://adwords.google.com/api/adwords/cm/v200909", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("rval")]
        public CampaignPage get(CampaignSelector selector) {
            object[] results = this.Invoke("get", new object[] {
                        selector});
            return ((CampaignPage)(results[0]));
        }
        
        /// <remarks/>
        public void getAsync(CampaignSelector selector) {
            this.getAsync(selector, null);
        }
        
        /// <remarks/>
        public void getAsync(CampaignSelector selector, object userState) {
            if ((this.getOperationCompleted == null)) {
                this.getOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOperationCompleted);
            }
            this.InvokeAsync("get", new object[] {
                        selector}, this.getOperationCompleted, userState);
        }
        
        private void OngetOperationCompleted(object arg) {
            if ((this.getCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCompleted(this, new getCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestHeader")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseHeader", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="https://adwords.google.com/api/adwords/cm/v200909", ResponseNamespace="https://adwords.google.com/api/adwords/cm/v200909", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("rval")]
        public CampaignReturnValue mutate([System.Xml.Serialization.XmlElementAttribute("operations")] CampaignOperation[] operations) {
            object[] results = this.Invoke("mutate", new object[] {
                        operations});
            return ((CampaignReturnValue)(results[0]));
        }
        
        /// <remarks/>
        public void mutateAsync(CampaignOperation[] operations) {
            this.mutateAsync(operations, null);
        }
        
        /// <remarks/>
        public void mutateAsync(CampaignOperation[] operations, object userState) {
            if ((this.mutateOperationCompleted == null)) {
                this.mutateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmutateOperationCompleted);
            }
            this.InvokeAsync("mutate", new object[] {
                        operations}, this.mutateOperationCompleted, userState);
        }
        
        private void OnmutateOperationCompleted(object arg) {
            if ((this.mutateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.mutateCompleted(this, new mutateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    [System.Xml.Serialization.XmlRootAttribute("RequestHeader", Namespace="https://adwords.google.com/api/adwords/cm/v200909", IsNullable=false)]
    public partial class MySoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string applicationTokenField;
        
        private string authTokenField;
        
        private string clientCustomerIdField;
        
        private string clientEmailField;
        
        private string developerTokenField;
        
        private string userAgentField;
        
        private bool validateOnlyField;
        
        private bool validateOnlyFieldSpecified;
        
        /// <remarks/>
        public string applicationToken {
            get {
                return this.applicationTokenField;
            }
            set {
                this.applicationTokenField = value;
            }
        }
        
        /// <remarks/>
        public string authToken {
            get {
                return this.authTokenField;
            }
            set {
                this.authTokenField = value;
            }
        }
        
        /// <remarks/>
        public string clientCustomerId {
            get {
                return this.clientCustomerIdField;
            }
            set {
                this.clientCustomerIdField = value;
            }
        }
        
        /// <remarks/>
        public string clientEmail {
            get {
                return this.clientEmailField;
            }
            set {
                this.clientEmailField = value;
            }
        }
        
        /// <remarks/>
        public string developerToken {
            get {
                return this.developerTokenField;
            }
            set {
                this.developerTokenField = value;
            }
        }
        
        /// <remarks/>
        public string userAgent {
            get {
                return this.userAgentField;
            }
            set {
                this.userAgentField = value;
            }
        }
        
        /// <remarks/>
        public bool validateOnly {
            get {
                return this.validateOnlyField;
            }
            set {
                this.validateOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validateOnlySpecified {
            get {
                return this.validateOnlyFieldSpecified;
            }
            set {
                this.validateOnlyFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CampaignReturnValue))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public abstract partial class ListReturnValue {
        
        private string listReturnValueTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ListReturnValue.Type")]
        public string ListReturnValueType {
            get {
                return this.listReturnValueTypeField;
            }
            set {
                this.listReturnValueTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class CampaignReturnValue : ListReturnValue {
        
        private Campaign[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public Campaign[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class Campaign {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        private CampaignStatus statusField;
        
        private bool statusFieldSpecified;
        
        private ServingStatus servingStatusField;
        
        private bool servingStatusFieldSpecified;
        
        private string startDateField;
        
        private string endDateField;
        
        private Budget budgetField;
        
        private BiddingStrategy biddingStrategyField;
        
        private AutoKeywordMatchingStatus autoKeywordMatchingStatusField;
        
        private bool autoKeywordMatchingStatusFieldSpecified;
        
        private Stats statsField;
        
        private AdServingOptimizationStatus adServingOptimizationStatusField;
        
        private bool adServingOptimizationStatusFieldSpecified;
        
        private FrequencyCap frequencyCapField;
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public CampaignStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ServingStatus servingStatus {
            get {
                return this.servingStatusField;
            }
            set {
                this.servingStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool servingStatusSpecified {
            get {
                return this.servingStatusFieldSpecified;
            }
            set {
                this.servingStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public Budget budget {
            get {
                return this.budgetField;
            }
            set {
                this.budgetField = value;
            }
        }
        
        /// <remarks/>
        public BiddingStrategy biddingStrategy {
            get {
                return this.biddingStrategyField;
            }
            set {
                this.biddingStrategyField = value;
            }
        }
        
        /// <remarks/>
        public AutoKeywordMatchingStatus autoKeywordMatchingStatus {
            get {
                return this.autoKeywordMatchingStatusField;
            }
            set {
                this.autoKeywordMatchingStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool autoKeywordMatchingStatusSpecified {
            get {
                return this.autoKeywordMatchingStatusFieldSpecified;
            }
            set {
                this.autoKeywordMatchingStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Stats stats {
            get {
                return this.statsField;
            }
            set {
                this.statsField = value;
            }
        }
        
        /// <remarks/>
        public AdServingOptimizationStatus adServingOptimizationStatus {
            get {
                return this.adServingOptimizationStatusField;
            }
            set {
                this.adServingOptimizationStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adServingOptimizationStatusSpecified {
            get {
                return this.adServingOptimizationStatusFieldSpecified;
            }
            set {
                this.adServingOptimizationStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FrequencyCap frequencyCap {
            get {
                return this.frequencyCapField;
            }
            set {
                this.frequencyCapField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public enum CampaignStatus {
        
        /// <remarks/>
        ACTIVE,
        
        /// <remarks/>
        DELETED,
        
        /// <remarks/>
        PAUSED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public enum ServingStatus {
        
        /// <remarks/>
        SERVING,
        
        /// <remarks/>
        NONE,
        
        /// <remarks/>
        ENDED,
        
        /// <remarks/>
        PENDING,
        
        /// <remarks/>
        SUSPENDED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class Budget {
        
        private BudgetBudgetPeriod periodField;
        
        private bool periodFieldSpecified;
        
        private Money amountField;
        
        private BudgetBudgetDeliveryMethod deliveryMethodField;
        
        private bool deliveryMethodFieldSpecified;
        
        /// <remarks/>
        public BudgetBudgetPeriod period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodSpecified {
            get {
                return this.periodFieldSpecified;
            }
            set {
                this.periodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Money amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public BudgetBudgetDeliveryMethod deliveryMethod {
            get {
                return this.deliveryMethodField;
            }
            set {
                this.deliveryMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deliveryMethodSpecified {
            get {
                return this.deliveryMethodFieldSpecified;
            }
            set {
                this.deliveryMethodFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Budget.BudgetPeriod", Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public enum BudgetBudgetPeriod {
        
        /// <remarks/>
        DAILY,
        
        /// <remarks/>
        MONTHLY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class Money : ComparableValue {
        
        private long microAmountField;
        
        private bool microAmountFieldSpecified;
        
        /// <remarks/>
        public long microAmount {
            get {
                return this.microAmountField;
            }
            set {
                this.microAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool microAmountSpecified {
            get {
                return this.microAmountFieldSpecified;
            }
            set {
                this.microAmountFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NumberValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LongValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoubleValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Money))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public abstract partial class ComparableValue {
        
        private string comparableValueTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ComparableValue.Type")]
        public string ComparableValueType {
            get {
                return this.comparableValueTypeField;
            }
            set {
                this.comparableValueTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LongValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoubleValue))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public abstract partial class NumberValue : ComparableValue {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class LongValue : NumberValue {
        
        private long numberField;
        
        private bool numberFieldSpecified;
        
        /// <remarks/>
        public long number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numberSpecified {
            get {
                return this.numberFieldSpecified;
            }
            set {
                this.numberFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class DoubleValue : NumberValue {
        
        private double numberField;
        
        private bool numberFieldSpecified;
        
        /// <remarks/>
        public double number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numberSpecified {
            get {
                return this.numberFieldSpecified;
            }
            set {
                this.numberFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Budget.BudgetDeliveryMethod", Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public enum BudgetBudgetDeliveryMethod {
        
        /// <remarks/>
        STANDARD,
        
        /// <remarks/>
        ACCELERATED,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BudgetOptimizer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ManualCPM))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ManualCPC))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConversionOptimizer))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public abstract partial class BiddingStrategy {
        
        private string biddingStrategyTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BiddingStrategy.Type")]
        public string BiddingStrategyType {
            get {
                return this.biddingStrategyTypeField;
            }
            set {
                this.biddingStrategyTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class BudgetOptimizer : BiddingStrategy {
        
        private Money bidCeilingField;
        
        /// <remarks/>
        public Money bidCeiling {
            get {
                return this.bidCeilingField;
            }
            set {
                this.bidCeilingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class ManualCPM : BiddingStrategy {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class ManualCPC : BiddingStrategy {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class ConversionOptimizer : BiddingStrategy {
        
        private PricingModel pricingModelField;
        
        private bool pricingModelFieldSpecified;
        
        /// <remarks/>
        public PricingModel pricingModel {
            get {
                return this.pricingModelField;
            }
            set {
                this.pricingModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pricingModelSpecified {
            get {
                return this.pricingModelFieldSpecified;
            }
            set {
                this.pricingModelFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public enum PricingModel {
        
        /// <remarks/>
        CLICKS,
        
        /// <remarks/>
        IMPRESSIONS,
        
        /// <remarks/>
        CONVERSIONS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public enum AutoKeywordMatchingStatus {
        
        /// <remarks/>
        OPT_IN,
        
        /// <remarks/>
        OPT_OUT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class Stats {
        
        private string startDateField;
        
        private string endDateField;
        
        private StatsNetwork networkField;
        
        private bool networkFieldSpecified;
        
        private long clicksField;
        
        private bool clicksFieldSpecified;
        
        private long impressionsField;
        
        private bool impressionsFieldSpecified;
        
        private Money costField;
        
        private double averagePositionField;
        
        private bool averagePositionFieldSpecified;
        
        private Money averageCpcField;
        
        private Money averageCpmField;
        
        private double ctrField;
        
        private bool ctrFieldSpecified;
        
        private long conversionsField;
        
        private bool conversionsFieldSpecified;
        
        private double conversionRateField;
        
        private bool conversionRateFieldSpecified;
        
        private Money costPerConversionField;
        
        private long conversionsManyPerClickField;
        
        private bool conversionsManyPerClickFieldSpecified;
        
        private double conversionRateManyPerClickField;
        
        private bool conversionRateManyPerClickFieldSpecified;
        
        private Money costPerConversionManyPerClickField;
        
        private string statsTypeField;
        
        /// <remarks/>
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public StatsNetwork network {
            get {
                return this.networkField;
            }
            set {
                this.networkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool networkSpecified {
            get {
                return this.networkFieldSpecified;
            }
            set {
                this.networkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long clicks {
            get {
                return this.clicksField;
            }
            set {
                this.clicksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clicksSpecified {
            get {
                return this.clicksFieldSpecified;
            }
            set {
                this.clicksFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long impressions {
            get {
                return this.impressionsField;
            }
            set {
                this.impressionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool impressionsSpecified {
            get {
                return this.impressionsFieldSpecified;
            }
            set {
                this.impressionsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Money cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
            }
        }
        
        /// <remarks/>
        public double averagePosition {
            get {
                return this.averagePositionField;
            }
            set {
                this.averagePositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool averagePositionSpecified {
            get {
                return this.averagePositionFieldSpecified;
            }
            set {
                this.averagePositionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Money averageCpc {
            get {
                return this.averageCpcField;
            }
            set {
                this.averageCpcField = value;
            }
        }
        
        /// <remarks/>
        public Money averageCpm {
            get {
                return this.averageCpmField;
            }
            set {
                this.averageCpmField = value;
            }
        }
        
        /// <remarks/>
        public double ctr {
            get {
                return this.ctrField;
            }
            set {
                this.ctrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ctrSpecified {
            get {
                return this.ctrFieldSpecified;
            }
            set {
                this.ctrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long conversions {
            get {
                return this.conversionsField;
            }
            set {
                this.conversionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool conversionsSpecified {
            get {
                return this.conversionsFieldSpecified;
            }
            set {
                this.conversionsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double conversionRate {
            get {
                return this.conversionRateField;
            }
            set {
                this.conversionRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool conversionRateSpecified {
            get {
                return this.conversionRateFieldSpecified;
            }
            set {
                this.conversionRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Money costPerConversion {
            get {
                return this.costPerConversionField;
            }
            set {
                this.costPerConversionField = value;
            }
        }
        
        /// <remarks/>
        public long conversionsManyPerClick {
            get {
                return this.conversionsManyPerClickField;
            }
            set {
                this.conversionsManyPerClickField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool conversionsManyPerClickSpecified {
            get {
                return this.conversionsManyPerClickFieldSpecified;
            }
            set {
                this.conversionsManyPerClickFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double conversionRateManyPerClick {
            get {
                return this.conversionRateManyPerClickField;
            }
            set {
                this.conversionRateManyPerClickField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool conversionRateManyPerClickSpecified {
            get {
                return this.conversionRateManyPerClickFieldSpecified;
            }
            set {
                this.conversionRateManyPerClickFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Money costPerConversionManyPerClick {
            get {
                return this.costPerConversionManyPerClickField;
            }
            set {
                this.costPerConversionManyPerClickField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stats.Type")]
        public string StatsType {
            get {
                return this.statsTypeField;
            }
            set {
                this.statsTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Stats.Network", Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public enum StatsNetwork {
        
        /// <remarks/>
        SEARCH,
        
        /// <remarks/>
        GOOGLE_SEARCH,
        
        /// <remarks/>
        SEARCH_NETWORK,
        
        /// <remarks/>
        CONTENT,
        
        /// <remarks/>
        CONTENT_KEYWORD_BID,
        
        /// <remarks/>
        CONTENT_PLACEMENT_BID,
        
        /// <remarks/>
        ALL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public enum AdServingOptimizationStatus {
        
        /// <remarks/>
        OPTIMIZE,
        
        /// <remarks/>
        ROTATE,
        
        /// <remarks/>
        UNAVAILABLE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class FrequencyCap {
        
        private long impressionsField;
        
        private bool impressionsFieldSpecified;
        
        private TimeUnit timeUnitField;
        
        private bool timeUnitFieldSpecified;
        
        private Level levelField;
        
        private bool levelFieldSpecified;
        
        /// <remarks/>
        public long impressions {
            get {
                return this.impressionsField;
            }
            set {
                this.impressionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool impressionsSpecified {
            get {
                return this.impressionsFieldSpecified;
            }
            set {
                this.impressionsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TimeUnit timeUnit {
            get {
                return this.timeUnitField;
            }
            set {
                this.timeUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeUnitSpecified {
            get {
                return this.timeUnitFieldSpecified;
            }
            set {
                this.timeUnitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Level level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool levelSpecified {
            get {
                return this.levelFieldSpecified;
            }
            set {
                this.levelFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public enum TimeUnit {
        
        /// <remarks/>
        MINUTE,
        
        /// <remarks/>
        HOUR,
        
        /// <remarks/>
        DAY,
        
        /// <remarks/>
        WEEK,
        
        /// <remarks/>
        MONTH,
        
        /// <remarks/>
        LIFETIME,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public enum Level {
        
        /// <remarks/>
        CREATIVE,
        
        /// <remarks/>
        ADGROUP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class Bid {
        
        private Money amountField;
        
        /// <remarks/>
        public Money amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ManualCPMAdGroupBids))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ManualCPCAdGroupBids))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConversionOptimizerAdGroupBids))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BudgetOptimizerAdGroupBids))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public abstract partial class AdGroupBids {
        
        private string adGroupBidsTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdGroupBids.Type")]
        public string AdGroupBidsType {
            get {
                return this.adGroupBidsTypeField;
            }
            set {
                this.adGroupBidsTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class ManualCPMAdGroupBids : AdGroupBids {
        
        private Bid maxCpmField;
        
        /// <remarks/>
        public Bid maxCpm {
            get {
                return this.maxCpmField;
            }
            set {
                this.maxCpmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class ManualCPCAdGroupBids : AdGroupBids {
        
        private Bid keywordMaxCpcField;
        
        private Bid keywordContentMaxCpcField;
        
        private Bid siteMaxCpcField;
        
        /// <remarks/>
        public Bid keywordMaxCpc {
            get {
                return this.keywordMaxCpcField;
            }
            set {
                this.keywordMaxCpcField = value;
            }
        }
        
        /// <remarks/>
        public Bid keywordContentMaxCpc {
            get {
                return this.keywordContentMaxCpcField;
            }
            set {
                this.keywordContentMaxCpcField = value;
            }
        }
        
        /// <remarks/>
        public Bid siteMaxCpc {
            get {
                return this.siteMaxCpcField;
            }
            set {
                this.siteMaxCpcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class ConversionOptimizerAdGroupBids : AdGroupBids {
        
        private Bid targetCpaField;
        
        /// <remarks/>
        public Bid targetCpa {
            get {
                return this.targetCpaField;
            }
            set {
                this.targetCpaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class BudgetOptimizerAdGroupBids : AdGroupBids {
        
        private Bid proxyKeywordMaxCpcField;
        
        private Bid proxySiteMaxCpcField;
        
        /// <remarks/>
        public Bid proxyKeywordMaxCpc {
            get {
                return this.proxyKeywordMaxCpcField;
            }
            set {
                this.proxyKeywordMaxCpcField = value;
            }
        }
        
        /// <remarks/>
        public Bid proxySiteMaxCpc {
            get {
                return this.proxySiteMaxCpcField;
            }
            set {
                this.proxySiteMaxCpcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConversionOptimizerBiddingTransition))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class BiddingTransition {
        
        private BiddingStrategy targetBiddingStrategyField;
        
        private AdGroupBids explicitAdGroupBidsField;
        
        private string biddingTransitionTypeField;
        
        /// <remarks/>
        public BiddingStrategy targetBiddingStrategy {
            get {
                return this.targetBiddingStrategyField;
            }
            set {
                this.targetBiddingStrategyField = value;
            }
        }
        
        /// <remarks/>
        public AdGroupBids explicitAdGroupBids {
            get {
                return this.explicitAdGroupBidsField;
            }
            set {
                this.explicitAdGroupBidsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BiddingTransition.Type")]
        public string BiddingTransitionType {
            get {
                return this.biddingTransitionTypeField;
            }
            set {
                this.biddingTransitionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class ConversionOptimizerBiddingTransition : BiddingTransition {
        
        private bool useSavedBidsField;
        
        private bool useSavedBidsFieldSpecified;
        
        /// <remarks/>
        public bool useSavedBids {
            get {
                return this.useSavedBidsField;
            }
            set {
                this.useSavedBidsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool useSavedBidsSpecified {
            get {
                return this.useSavedBidsFieldSpecified;
            }
            set {
                this.useSavedBidsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CampaignOperation))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public abstract partial class Operation {
        
        private Operator operatorField;
        
        private bool operatorFieldSpecified;
        
        private string operationTypeField;
        
        /// <remarks/>
        public Operator @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operatorSpecified {
            get {
                return this.operatorFieldSpecified;
            }
            set {
                this.operatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Operation.Type")]
        public string OperationType {
            get {
                return this.operationTypeField;
            }
            set {
                this.operationTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public enum Operator {
        
        /// <remarks/>
        ADD,
        
        /// <remarks/>
        REMOVE,
        
        /// <remarks/>
        SET,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class CampaignOperation : Operation {
        
        private BiddingTransition biddingTransitionField;
        
        private Campaign operandField;
        
        /// <remarks/>
        public BiddingTransition biddingTransition {
            get {
                return this.biddingTransitionField;
            }
            set {
                this.biddingTransitionField = value;
            }
        }
        
        /// <remarks/>
        public Campaign operand {
            get {
                return this.operandField;
            }
            set {
                this.operandField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CampaignPage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public abstract partial class Page {
        
        private int totalNumEntriesField;
        
        private bool totalNumEntriesFieldSpecified;
        
        private string pageTypeField;
        
        /// <remarks/>
        public int totalNumEntries {
            get {
                return this.totalNumEntriesField;
            }
            set {
                this.totalNumEntriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalNumEntriesSpecified {
            get {
                return this.totalNumEntriesFieldSpecified;
            }
            set {
                this.totalNumEntriesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Page.Type")]
        public string PageType {
            get {
                return this.pageTypeField;
            }
            set {
                this.pageTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class CampaignPage : Page {
        
        private Budget totalBudgetField;
        
        private Campaign[] entriesField;
        
        /// <remarks/>
        public Budget totalBudget {
            get {
                return this.totalBudgetField;
            }
            set {
                this.totalBudgetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entries")]
        public Campaign[] entries {
            get {
                return this.entriesField;
            }
            set {
                this.entriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class Paging {
        
        private int startIndexField;
        
        private bool startIndexFieldSpecified;
        
        private int numberResultsField;
        
        private bool numberResultsFieldSpecified;
        
        /// <remarks/>
        public int startIndex {
            get {
                return this.startIndexField;
            }
            set {
                this.startIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startIndexSpecified {
            get {
                return this.startIndexFieldSpecified;
            }
            set {
                this.startIndexFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int numberResults {
            get {
                return this.numberResultsField;
            }
            set {
                this.numberResultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numberResultsSpecified {
            get {
                return this.numberResultsFieldSpecified;
            }
            set {
                this.numberResultsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class DateRange {
        
        private string minField;
        
        private string maxField;
        
        /// <remarks/>
        public string min {
            get {
                return this.minField;
            }
            set {
                this.minField = value;
            }
        }
        
        /// <remarks/>
        public string max {
            get {
                return this.maxField;
            }
            set {
                this.maxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class StatsSelector {
        
        private DateRange dateRangeField;
        
        private string statsSelectorTypeField;
        
        /// <remarks/>
        public DateRange dateRange {
            get {
                return this.dateRangeField;
            }
            set {
                this.dateRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StatsSelector.Type")]
        public string StatsSelectorType {
            get {
                return this.statsSelectorTypeField;
            }
            set {
                this.statsSelectorTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    public partial class CampaignSelector {
        
        private long[] idsField;
        
        private CampaignStatus[] campaignStatusesField;
        
        private StatsSelector statsSelectorField;
        
        private Paging pagingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ids")]
        public long[] ids {
            get {
                return this.idsField;
            }
            set {
                this.idsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("campaignStatuses")]
        public CampaignStatus[] campaignStatuses {
            get {
                return this.campaignStatusesField;
            }
            set {
                this.campaignStatusesField = value;
            }
        }
        
        /// <remarks/>
        public StatsSelector statsSelector {
            get {
                return this.statsSelectorField;
            }
            set {
                this.statsSelectorField = value;
            }
        }
        
        /// <remarks/>
        public Paging paging {
            get {
                return this.pagingField;
            }
            set {
                this.pagingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v200909")]
    [System.Xml.Serialization.XmlRootAttribute("ResponseHeader", Namespace="https://adwords.google.com/api/adwords/cm/v200909", IsNullable=false)]
    public partial class MySoapResponseHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string requestIdField;
        
        private long operationsField;
        
        private bool operationsFieldSpecified;
        
        private long responseTimeField;
        
        private bool responseTimeFieldSpecified;
        
        private long unitsField;
        
        private bool unitsFieldSpecified;
        
        /// <remarks/>
        public string requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        public long operations {
            get {
                return this.operationsField;
            }
            set {
                this.operationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operationsSpecified {
            get {
                return this.operationsFieldSpecified;
            }
            set {
                this.operationsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long responseTime {
            get {
                return this.responseTimeField;
            }
            set {
                this.responseTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool responseTimeSpecified {
            get {
                return this.responseTimeFieldSpecified;
            }
            set {
                this.responseTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unitsSpecified {
            get {
                return this.unitsFieldSpecified;
            }
            set {
                this.unitsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getCompletedEventHandler(object sender, getCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CampaignPage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CampaignPage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void mutateCompletedEventHandler(object sender, mutateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class mutateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal mutateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CampaignReturnValue Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CampaignReturnValue)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591