//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easynet.Edge.Services.Google.Adwords.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://adwords.google.com/api/adwords/v13/AccountService")]
        public string Edge_Services_Google_Adwords_GAdWordsAccountServiceV13_AccountService {
            get {
                return ((string)(this["Edge_Services_Google_Adwords_GAdWordsAccountServiceV13_AccountService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://adwords.google.com/api/adwords/v13/ReportService")]
        public string Edge_Services_Google_Adwords_GAdWordsReportServiceV13_ReportService {
            get {
                return ((string)(this["Edge_Services_Google_Adwords_GAdWordsReportServiceV13_ReportService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://adwords.google.com/api/adwords/cm/v200909/CampaignService")]
        public string Edge_Services_Google_Adwords_com_google_adwords_CampaignService {
            get {
                return ((string)(this["Edge_Services_Google_Adwords_com_google_adwords_CampaignService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://adwords.google.com/api/adwords/cm/v200909/AdGroupService")]
        public string Edge_Services_Google_Adwords_AdGroupWS_AdGroupService {
            get {
                return ((string)(this["Edge_Services_Google_Adwords_AdGroupWS_AdGroupService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://adwords.google.com/api/adwords/cm/v200909/AdGroupAdService")]
        public string Edge_Services_Google_Adwords_AdGroupAdService_AdGroupAdService {
            get {
                return ((string)(this["Edge_Services_Google_Adwords_AdGroupAdService_AdGroupAdService"]));
            }
        }
    }
}
