//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdgeBI.Wizards.Utils.WizardTester.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DataSource=qa")]
        public string AnalysisServerConnectionString {
            get {
                return ((string)(this["AnalysisServerConnectionString"]));
            }
            set {
                this["AnalysisServerConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("easynet_UDM")]
        public string AnalysisServerDatabase {
            get {
                return ((string)(this["AnalysisServerDatabase"]));
            }
            set {
                this["AnalysisServerDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BO")]
        public string CubeNameStartWith {
            get {
                return ((string)(this["CubeNameStartWith"]));
            }
            set {
                this["CubeNameStartWith"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BOTemplate3")]
        public string CubeTemplatesBOTemplate {
            get {
                return ((string)(this["CubeTemplatesBOTemplate"]));
            }
            set {
                this["CubeTemplatesBOTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regs")]
        public string CPA1 {
            get {
                return ((string)(this["CPA1"]));
            }
            set {
                this["CPA1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Actives")]
        public string CPA2 {
            get {
                return ((string)(this["CPA2"]));
            }
            set {
                this["CPA2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BO New Activations1")]
        public string BookName {
            get {
                return ((string)(this["BookName"]));
            }
            set {
                this["BookName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\gidi-pc\\d$\\Program Files\\Panorama\\E-BI\\books\\BO PPC VS BCK")]
        public string BookTemplatePath {
            get {
                return ((string)(this["BookTemplatePath"]));
            }
            set {
                this["BookTemplatePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BackUpName {
            get {
                return ((string)(this["BackUpName"]));
            }
            set {
                this["BackUpName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\gidi-pc\\d$\\Program Files\\Panorama\\E-BI\\Panorama.msc")]
        public string PanoramaExecutionPath {
            get {
                return ((string)(this["PanoramaExecutionPath"]));
            }
            set {
                this["PanoramaExecutionPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\gidi-pc\\d$\\Program Files\\Panorama\\E-BI\\Applications.xml")]
        public string ApplicationsXmlPath {
            get {
                return ((string)(this["ApplicationsXmlPath"]));
            }
            set {
                this["ApplicationsXmlPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\hal\\d$\\ssis_projects\\Pkg_3000_Process_BOPPC_Cubes-Template.dtsx")]
        public string DtsxTemplatePath {
            get {
                return ((string)(this["DtsxTemplatePath"]));
            }
            set {
                this["DtsxTemplatePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\hal\\d$\\ssis_projects\\Pkg_3000_Process_BOPPC_Cubes.dtsx")]
        public string DtsxPath {
            get {
                return ((string)(this["DtsxPath"]));
            }
            set {
                this["DtsxPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BOPPCCube888")]
        public string CubeNamePattenToReplace {
            get {
                return ((string)(this["CubeNamePattenToReplace"]));
            }
            set {
                this["CubeNamePattenToReplace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("easynet_UDM")]
        public string DatabaseNamePattenToReplace {
            get {
                return ((string)(this["DatabaseNamePattenToReplace"]));
            }
            set {
                this["DatabaseNamePattenToReplace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\BIadmin\\Desktop\\Codebase-2010\\Applications\\EdgeServiceHost\\bin\\Debug\\Edg" +
            "eServiceHost.exe")]
        public string ServiceHostPath {
            get {
                return ((string)(this["ServiceHostPath"]));
            }
            set {
                this["ServiceHostPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Edge\\BIadmin")]
        public string RoleMemberName {
            get {
                return ((string)(this["RoleMemberName"]));
            }
            set {
                this["RoleMemberName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Signups,Leads,Purchase,Conversions")]
        public string CombosValues {
            get {
                return ((string)(this["CombosValues"]));
            }
            set {
                this["CombosValues"] = value;
            }
        }
    }
}
